$(function(){
    $("#m1").click(function(e){
        $("#jezek").fadeIn("slow");
        $("#weizenbier").fadeOut("slow");
        $("#dark").fadeOut("slow");
        $("#premium").fadeOut("slow");
        $("#stout").fadeOut("slow");
        $("#petainer").fadeOut("slow");
        e.preventDefault();
    });
    $("#m2").click(function(e){
        $("#weizenbier").fadeIn("slow");
        $("#jezek").fadeOut("slow");
        $("#dark").fadeOut("slow");
        $("#premium").fadeOut("slow");
        $("#stout").fadeOut("slow");
        $("#petainer").fadeOut("slow");
        e.preventDefault();
    });
    $("#m3").click(function(e){
        $("#dark").fadeIn("slow");
        $("#weizenbier").fadeOut("slow");
        $("#jezek").fadeOut("slow");
        $("#premium").fadeOut("slow");
        $("#stout").fadeOut("slow");
        $("#petainer").fadeOut("slow");
        e.preventDefault();
    });
    $("#m4").click(function(e){
        $("#premium").fadeIn("slow");
        $("#weizenbier").fadeOut("slow");
        $("#dark").fadeOut("slow");
        $("#jezek").fadeOut("slow");
        $("#stout").fadeOut("slow");
        $("#petainer").fadeOut("slow");
        e.preventDefault();
    });
    $("#m5").click(function(e){
        $("#stout").fadeIn("slow");
        $("#weizenbier").fadeOut("slow");
        $("#dark").fadeOut("slow");
        $("#premium").fadeOut("slow");
        $("#jezek").fadeOut("slow");
        $("#petainer").fadeOut("slow");
        e.preventDefault();
    });
    $("#m6").click(function(e){
        $("#petainer").fadeIn("slow");
        $("#weizenbier").fadeOut("slow");
        $("#dark").fadeOut("slow");
        $("#premium").fadeOut("slow");
        $("#stout").fadeOut("slow");
        $("#jezek").fadeOut("slow");
        e.preventDefault();
    });
});